# Automatically generated by
#  dockerfile-to-powershell.py -d ./Dockerfile -p dockerfile-to-powershell-generated-sample.ps1 -a WINDOWS_VERSION=1809 -a DD_TARGET_ARCH=x64 
#  on 06/27/2022 10:22:15

# WARNING!!!
#  If this script had been generated from ...
#      https://github.com/DataDog/datadog-agent-buildimages/blob/main/windows/Dockerfile
#  ... which is currently based ...
#      on mcr.microsoft.com/dotnet/framework/runtime:4.8-windowsservercore-ltsc2019
#  ... image, then you will need to install .NET 4.8 before running it from one of three sources
#     * https://dotnet.microsoft.com/en-us/download/dotnet-framework/net48
#     * https://support.microsoft.com/en-us/topic/microsoft-net-framework-4-8-offline-installer-for-windows-9d23f658-3b97-68ab-d013-aa3c3e7495e0
#     * https://github.com/microsoft/dotnet-framework-docker/blob/528e53c63f429860d99d55409b0018d225059f0c/src/runtime/4.8/windowsservercore-ltsc2019/Dockerfile
#
#  Similarly, for other Dockerfiles you need to make sure that you prepare Windows machine to
#  be matching its Dockerfile's BASE image.
#
#  If you try to run this script more than once some commands may fail and break the script.
#  It may be addressed better in the future but for now you may need to comment out offending
#  commands. If after running generated from the Dockerfile Powershell script the Dockerfile
#  had been modified and you wish to apply these changes, then in contrast to applying newly
#  generated Powershell script your mileage may vary (and it depends very much on the Dockerfile
#  content) ...
#    * It may actually just work
#    * You may need to comment out everything except the difference between old and new
#      Powershell script
#    * You may need to explicitly uninstall or remove previously deployed applications, files
#      or other artifacts
#
# Usage: .\<this-script.ps1> -DockerRepoPath <repo path>
#    -DockerRepoPath is required parameter. You need to clone the
#    same repo as the one used for building Docker image.
#    Specifically it is https://github.com/DataDog/datadog-agent-buildimages
Param(
    [Parameter(Mandatory)]
    [string]
    $DockerRepoPath
)

$DockerRepoPathExists = Test-Path $DockerRepoPath
if (!$DockerRepoPathExists) {
    Write-Host "Provided 'DockerRepoPath' ($DockerRepoPath) path does not exist. Please provide valid argument"
    Exit
}
   
# Save current location and sync it to .NET current location (it is not automatic and needed in some cases)
#    https://stackoverflow.com/questions/11246068/why-dont-net-objects-in-powershell-use-the-current-directory
$origLocation = Get-Location
[Environment]::CurrentDirectory = $origLocation
# Currently Docker run everything in the root. And we have to keep it this way
Set-Location $origLocation

$totalStopwatch = [system.diagnostics.stopwatch]::StartNew()

function Update-SessionEnvironment {
   foreach ($s in 'Machine','User') {
      [Environment]::GetEnvironmentVariables($s).GetEnumerator().
      Where({$_.Key -ne 'PATH'}) | ForEach-Object {
      [Environment]::SetEnvironmentVariable($_.Key,$_.Value,'Process') }}

   $env:PATH = ( ('Machine','User').ForEach({
      [Environment]::GetEnvironmentVariable('PATH',$_)}).
      Split(';').Where({$_}) | Select-Object -Unique ) -join ';'
}
# Use the Microsoft-provided .NET Runtime 4.8 image as the base image
# because installing it in the image with Chocolatey requires a reboot.
# There is a bug in the February 11, 2020 update that makes commands fail in
# docker containers (see: https://support.microsoft.com/en-us/help/4542617/you-might-encounter-issues-when-using-windows-server-containers-with-t)
# To avoid that, there are two solutions:
# - both the host and the container must have the February 11, 2020 update, or
# - neither the host and the container must have the February 11, 2020 update.
# Since our 1809 windows-docker host image does not have this update, we use a base
# container image that does not have this update either (thus the 20200114 tag).
# On the contrary, since our 1909 windows-docker host image does have this update,
# we use a base container image that does have this update.
# TODO: Once the 1809 windows-docker host image is updated, update the base container image.
# Content: ARG BASE_IMAGE=mcr.microsoft.com/dotnet/framework/runtime:4.8-windowsservercore-ltsc2019

# Content: FROM ${BASE_IMAGE}
# Base Image: ${BASE_IMAGE}

# Content: SHELL ["powershell", "-Command"]
# SHELL="powershell -Command"

# Content: ARG WINDOWS_VERSION
# ARG=1809

# Content: ENV WINDOWS_VERSION=${WINDOWS_VERSION:-1809}
[System.Environment]::SetEnvironmentVariable('WINDOWS_VERSION','1809')

# Content: ARG DD_TARGET_ARCH
# ARG=x64

# Content: ENV TARGET_ARCH=${DD_TARGET_ARCH:-x64}
[System.Environment]::SetEnvironmentVariable('TARGET_ARCH','x64')

# Content: ENV GIT_VERSION "2.26.2"
[System.Environment]::SetEnvironmentVariable('GIT_VERSION','2.26.2')

# Content: ENV GIT_SHA256 "2dfbb1c46547c70179442a92b8593d592292b8bce2fd02ac4e0051a8072dde8f"
[System.Environment]::SetEnvironmentVariable('GIT_SHA256','2dfbb1c46547c70179442a92b8593d592292b8bce2fd02ac4e0051a8072dde8f')

# Content: ENV SEVENZIP_VERSION "19.0.0"
[System.Environment]::SetEnvironmentVariable('SEVENZIP_VERSION','19.0.0')

# Content: ENV SEVENZIP_SHA256 "0f5d4dbbe5e55b7aa31b91e5925ed901fdf46a367491d81381846f05ad54c45e"
[System.Environment]::SetEnvironmentVariable('SEVENZIP_SHA256','0f5d4dbbe5e55b7aa31b91e5925ed901fdf46a367491d81381846f05ad54c45e')

# Content: ENV VS2017BUILDTOOLS_VERSION "16.8.3.0"
[System.Environment]::SetEnvironmentVariable('VS2017BUILDTOOLS_VERSION','16.8.3.0')

# Content: ENV VS2017BUILDTOOLS_SHA256 "ccfb9355f4f753315455542f966025f96de734292d3908c8c3717e9685b709f0"
[System.Environment]::SetEnvironmentVariable('VS2017BUILDTOOLS_SHA256','ccfb9355f4f753315455542f966025f96de734292d3908c8c3717e9685b709f0')

#ENV VS2017BUILDTOOLS_DOWNLOAD_URL "https://download.visualstudio.microsoft.com/download/pr/d0eac510-174b-4241-b73b-93dc7cc1fbf7/9822b4c851e14d9658babd1533f66f518c6169196e985fe5713b2774128832ae/vs_BuildTools.exe"
# Content: ENV VS2017BUILDTOOLS_DOWNLOAD_URL "https://download.visualstudio.microsoft.com/download/pr/9b3476ff-6d0a-4ff8-956d-270147f21cd4/ccfb9355f4f753315455542f966025f96de734292d3908c8c3717e9685b709f0/vs_BuildTools.exe"
[System.Environment]::SetEnvironmentVariable('VS2017BUILDTOOLS_DOWNLOAD_URL','https://download.visualstudio.microsoft.com/download/pr/9b3476ff-6d0a-4ff8-956d-270147f21cd4/ccfb9355f4f753315455542f966025f96de734292d3908c8c3717e9685b709f0/vs_BuildTools.exe')

# Content: ENV GO_VERSION "1.17.11"
[System.Environment]::SetEnvironmentVariable('GO_VERSION','1.17.11')

# Content: ENV GO_SHA256 "88e60b92069d8e0932ca5d8bd8227d1693b9570fa2afbedadcc680749c428d54"
[System.Environment]::SetEnvironmentVariable('GO_SHA256','88e60b92069d8e0932ca5d8bd8227d1693b9570fa2afbedadcc680749c428d54')

# Content: ENV RUBY_VERSION "2.6.6-1"
[System.Environment]::SetEnvironmentVariable('RUBY_VERSION','2.6.6-1')

# Content: ENV RUBY_SHA256 "fbdf77a3e1fa36e25cf0af1303ac76f67dec7a6f739a829784a299702cad1492"
[System.Environment]::SetEnvironmentVariable('RUBY_SHA256','fbdf77a3e1fa36e25cf0af1303ac76f67dec7a6f739a829784a299702cad1492')

# Content: ENV IBM_MQ_VERSION "9.2.4.0"
[System.Environment]::SetEnvironmentVariable('IBM_MQ_VERSION','9.2.4.0')

# Content: ENV IBM_MQ_SHA256 "9cea7e1693d051437e78468fd5e915b7b7ed2baf36cdae4936bcf2b760f55daa"
[System.Environment]::SetEnvironmentVariable('IBM_MQ_SHA256','9cea7e1693d051437e78468fd5e915b7b7ed2baf36cdae4936bcf2b760f55daa')

# Content: ENV PYTHON_VERSION "3.8.2"
[System.Environment]::SetEnvironmentVariable('PYTHON_VERSION','3.8.2')

# Content: ENV PYTHON_SHA256 "8e400e3f32cdcb746e62e0db4d3ae4cba1f927141ebc4d0d5a4006b0daee8921"
[System.Environment]::SetEnvironmentVariable('PYTHON_SHA256','8e400e3f32cdcb746e62e0db4d3ae4cba1f927141ebc4d0d5a4006b0daee8921')

# Content: ENV WIX_VERSION "3.11.2"
[System.Environment]::SetEnvironmentVariable('WIX_VERSION','3.11.2')

# Content: ENV WIX_SHA256 "32bb76c478fcb356671d4aaf006ad81ca93eea32c22a9401b168fc7471feccd2"
[System.Environment]::SetEnvironmentVariable('WIX_SHA256','32bb76c478fcb356671d4aaf006ad81ca93eea32c22a9401b168fc7471feccd2')

# Content: ENV CMAKE_VERSION "3.23.0"
[System.Environment]::SetEnvironmentVariable('CMAKE_VERSION','3.23.0')

# Content: ENV CMAKE_SHA256 "1e772025844f1cc648d28f42090038e5ca5cf72e2889de26d8d05ee25da17061"
[System.Environment]::SetEnvironmentVariable('CMAKE_SHA256','1e772025844f1cc648d28f42090038e5ca5cf72e2889de26d8d05ee25da17061')

# Content: ENV MSYS_VERSION "20210725"
[System.Environment]::SetEnvironmentVariable('MSYS_VERSION','20210725')

# Content: ENV MSYS_SHA256 "4013a9d5e51b448343efc24fc6a324cc999bb96b4c01b13a6bd3c661bb5c8a82"
[System.Environment]::SetEnvironmentVariable('MSYS_SHA256','4013a9d5e51b448343efc24fc6a324cc999bb96b4c01b13a6bd3c661bb5c8a82')

# Content: ENV NUGET_VERSION "5.8.0"
[System.Environment]::SetEnvironmentVariable('NUGET_VERSION','5.8.0')

# Content: ENV NUGET_SHA256 "5c5b9c96165d3283b2cb9e5b65825d343e0e7139b9e70a250b4bb24c2285f3ba"
[System.Environment]::SetEnvironmentVariable('NUGET_SHA256','5c5b9c96165d3283b2cb9e5b65825d343e0e7139b9e70a250b4bb24c2285f3ba')

# Content: ENV WINGET_VERSION "1.0.4.0"
[System.Environment]::SetEnvironmentVariable('WINGET_VERSION','1.0.4.0')

# Content: ENV WINGET_SHA256 "8a4b727a8ad588c86603136a5d48093b59ed7491f7c5dc9f13725da0900fe6ab"
[System.Environment]::SetEnvironmentVariable('WINGET_SHA256','8a4b727a8ad588c86603136a5d48093b59ed7491f7c5dc9f13725da0900fe6ab')

# Content: ENV EMBEDDED_PYTHON_2_VERSION "2.7.17"
[System.Environment]::SetEnvironmentVariable('EMBEDDED_PYTHON_2_VERSION','2.7.17')

# Content: ENV EMBEDDED_PYTHON_2_SHA256 "557ea6690c5927360656c003d3114b73adbd755b712a2911975dde813d6d7afb"
[System.Environment]::SetEnvironmentVariable('EMBEDDED_PYTHON_2_SHA256','557ea6690c5927360656c003d3114b73adbd755b712a2911975dde813d6d7afb')

# Content: ENV EMBEDDED_PYTHON_3_VERSION "3.8.1"
[System.Environment]::SetEnvironmentVariable('EMBEDDED_PYTHON_3_VERSION','3.8.1')

# Content: ENV EMBEDDED_PYTHON_3_SHA256 "58563ca60891025923572107e02b8f07439928eb5222dd10466cc92089072c2a"
[System.Environment]::SetEnvironmentVariable('EMBEDDED_PYTHON_3_SHA256','58563ca60891025923572107e02b8f07439928eb5222dd10466cc92089072c2a')

# Content: ENV EMBEDDED_PIP_VERSION "20.3.4"
[System.Environment]::SetEnvironmentVariable('EMBEDDED_PIP_VERSION','20.3.4')

# Content: ENV CACERTS_HASH "2e6381065877c8ba5ae863552f15da6ba8b49f71704b4f92896f4fd0138a1b7c"
[System.Environment]::SetEnvironmentVariable('CACERTS_HASH','2e6381065877c8ba5ae863552f15da6ba8b49f71704b4f92896f4fd0138a1b7c')

# Content: ENV CACERTS_VERSION "2022-04-26"
[System.Environment]::SetEnvironmentVariable('CACERTS_VERSION','2022-04-26')

# Content: LABEL target_agent="Agent 6/7"
# LABEL resolved: target_agent='Agent 6/7'

# Content: LABEL target_arch=${TARGET_ARCH}
# LABEL resolved: target_arch='x64'

# Content: LABEL windows_version=${WINDOWS_VERSION}
# LABEL resolved: windows_version='1809'

# Content: LABEL git_version=${GIT_VERSION}
# LABEL resolved: git_version='2.26.2'

# Content: LABEL sevenzip_version=${SEVENZIP_VERSION}
# LABEL resolved: sevenzip_version='19.0.0'

# Content: LABEL vs2017buildtools_version=${VS2017BUILDTOOLS_VERSION}
# LABEL resolved: vs2017buildtools_version='16.8.3.0'

# Content: LABEL go_version=${GO_VERSION}
# LABEL resolved: go_version='1.17.11'

# Content: LABEL ruby_version=${RUBY_VERSION}
# LABEL resolved: ruby_version='2.6.6-1'

# Content: LABEL wix_version=${WIX_VERSION}
# LABEL resolved: wix_version='3.11.2'

# Content: LABEL cmake_version=${CMAKE_VERSION}
# LABEL resolved: cmake_version='3.23.0'

# Content: LABEL msys_version=${MSYS_VERSION}
# LABEL resolved: msys_version='20210725'

# Content: LABEL system_python_version=${PYTHON_VERSION}
# LABEL resolved: system_python_version='3.8.2'

# Content: LABEL embedded_py2_version=${EMBEDDED_PYTHON_2_VERSION}
# LABEL resolved: embedded_py2_version='2.7.17'

# Content: LABEL embedded_py3_version=${EMBEDDED_PYTHON_3_VERSION}
# LABEL resolved: embedded_py3_version='3.8.1'

# Content: LABEL nuget_version=${NUGET_VERSION}
# LABEL resolved: nuget_version='5.8.0'

# Add certificates needed for build & check certificates file hash
# We need to trust the DigiCert High Assurance EV Root CA certificate, which signs python.org,
# to be able to download some Python components during the Agent build.
# Content: RUN (New-Object System.Net.WebClient).DownloadFile(\"https://curl.haxx.se/ca/cacert-${ENV:CACERTS_VERSION}.pem\", \"cacert.pem\")
$stopwatch = [system.diagnostics.stopwatch]::StartNew()
Write-Host @'
Starting to (New-Object System.Net.WebClient).DownloadFile("https://curl.haxx.se/ca/cacert-${ENV:CACERTS_VERSION}.pem", "cacert.pem")
 ...
'@
(New-Object System.Net.WebClient).DownloadFile("https://curl.haxx.se/ca/cacert-${ENV:CACERTS_VERSION}.pem", "cacert.pem")
# Restore location and reload environment in case if they were changed
Set-Location $origLocation
# [Environment]::CurrentDirectory = $origLocation ## In some future cases this line may need to be executed
Update-SessionEnvironment
# Measure taken time
$stopwatch.Stop()
$timeTaken = $stopwatch.Elapsed.ToString("dd\.hh\:mm\:ss")
Write-Host "... this step executed in $timeTaken`n"

# Content: RUN if ((Get-FileHash -Algorithm SHA256 .\cacert.pem).Hash -ne \"$ENV:CACERTS_HASH\") { Write-Host \"Wrong hashsum for cacert.pem: got '$((Get-FileHash -Algorithm SHA256 .\cacert.pem).Hash)', expected '$ENV:CACERTS_HASH'.\"; exit 1 }
$stopwatch = [system.diagnostics.stopwatch]::StartNew()
Write-Host @'
Starting to if ((Get-FileHash -Algorithm SHA256 .\cacert.pem).Hash -ne "$ENV:CACERTS_HASH") { Write-Host "Wrong hashsum for cacert.pem: got '$((Get-FileHash -Algorithm SHA256 .\cacert.pem).Hash)', expected '$ENV:CACERTS_HASH'."; exit 1 }
 ...
'@
if ((Get-FileHash -Algorithm SHA256 .\cacert.pem).Hash -ne "$ENV:CACERTS_HASH") { Write-Host "Wrong hashsum for cacert.pem: got '$((Get-FileHash -Algorithm SHA256 .\cacert.pem).Hash)', expected '$ENV:CACERTS_HASH'."; exit 1 }
# Restore location and reload environment in case if they were changed
Set-Location $origLocation
# [Environment]::CurrentDirectory = $origLocation ## In some future cases this line may need to be executed
Update-SessionEnvironment
# Measure taken time
$stopwatch.Stop()
$timeTaken = $stopwatch.Elapsed.ToString("dd\.hh\:mm\:ss")
Write-Host "... this step executed in $timeTaken`n"

# Content: RUN setx SSL_CERT_FILE \"C:\cacert.pem\"
$stopwatch = [system.diagnostics.stopwatch]::StartNew()
Write-Host @'
Starting to setx SSL_CERT_FILE "C:\cacert.pem"
 ...
'@
setx SSL_CERT_FILE "C:\cacert.pem"
# Restore location and reload environment in case if they were changed
Set-Location $origLocation
# [Environment]::CurrentDirectory = $origLocation ## In some future cases this line may need to be executed
Update-SessionEnvironment
# Measure taken time
$stopwatch.Stop()
$timeTaken = $stopwatch.Elapsed.ToString("dd\.hh\:mm\:ss")
Write-Host "... this step executed in $timeTaken`n"

### Preliminary step: we need both the .NET 3.5 runtime and
### the .NET 4.8 runtime. To do this, we get 4.8 from a base image and we
### manually the install .NET Framework 3.5 runtime using the instructions in
### the mcr.microsoft.com/dotnet/framework/runtime:3.5 Dockerfile:
### https://github.com/microsoft/dotnet-framework-docker/blob/26597e42d157cc1e09d1e0dc8f23c32e6c3d1467/3.5/runtime/windowsservercore-ltsc2019/Dockerfile
### The .NET Fx 3.5 is needed for the Visual C++ Compiler for Python 2.7
### (https://www.microsoft.com/en-us/download/details.aspx?id=44266)
### and to work around a bug in the WiX 3.11 installer
### (https://github.com/wixtoolset/issues/issues/5661).
# Install .NET Fx 3.5
# Content: COPY ./windows/install_net35.ps1 install_net35.ps1
Write-Host @'
Starting to copy $DockerRepoPath\.\windows\install_net35.ps1 install_net35.ps1 ...
'@
copy $DockerRepoPath\.\windows\install_net35.ps1 install_net35.ps1
Write-Host

# Content: RUN Powershell -C .\install_net35.ps1
$stopwatch = [system.diagnostics.stopwatch]::StartNew()
Write-Host @'
Starting to .\install_net35.ps1
 ...
'@
.\install_net35.ps1
# Restore location and reload environment in case if they were changed
Set-Location $origLocation
# [Environment]::CurrentDirectory = $origLocation ## In some future cases this line may need to be executed
Update-SessionEnvironment
# Measure taken time
$stopwatch.Stop()
$timeTaken = $stopwatch.Elapsed.ToString("dd\.hh\:mm\:ss")
Write-Host "... this step executed in $timeTaken`n"

### End of preliminary step
# Install 7-zip
# Content: Copy ./windows/install_7zip.ps1 install_7zip.ps1
Write-Host @'
Starting to copy $DockerRepoPath\.\windows\install_7zip.ps1 install_7zip.ps1 ...
'@
copy $DockerRepoPath\.\windows\install_7zip.ps1 install_7zip.ps1
Write-Host

# Content: RUN powershell -Command .\install_7zip.ps1 -Version $ENV:SEVENZIP_VERSION -Sha256 $ENV:SEVENZIP_SHA256
$stopwatch = [system.diagnostics.stopwatch]::StartNew()
Write-Host @'
Starting to .\install_7zip.ps1 -Version $ENV:SEVENZIP_VERSION -Sha256 $ENV:SEVENZIP_SHA256
 ...
'@
.\install_7zip.ps1 -Version $ENV:SEVENZIP_VERSION -Sha256 $ENV:SEVENZIP_SHA256
# Restore location and reload environment in case if they were changed
Set-Location $origLocation
# [Environment]::CurrentDirectory = $origLocation ## In some future cases this line may need to be executed
Update-SessionEnvironment
# Measure taken time
$stopwatch.Stop()
$timeTaken = $stopwatch.Elapsed.ToString("dd\.hh\:mm\:ss")
Write-Host "... this step executed in $timeTaken`n"

# Install git
# Content: COPY ./windows/install_mingit.ps1 install_mingit.ps1
Write-Host @'
Starting to copy $DockerRepoPath\.\windows\install_mingit.ps1 install_mingit.ps1 ...
'@
copy $DockerRepoPath\.\windows\install_mingit.ps1 install_mingit.ps1
Write-Host

# Content: RUN powershell -Command .\install_mingit.ps1 -Version $ENV:GIT_VERSION -Sha256 $ENV:GIT_SHA256
$stopwatch = [system.diagnostics.stopwatch]::StartNew()
Write-Host @'
Starting to .\install_mingit.ps1 -Version $ENV:GIT_VERSION -Sha256 $ENV:GIT_SHA256
 ...
'@
.\install_mingit.ps1 -Version $ENV:GIT_VERSION -Sha256 $ENV:GIT_SHA256
# Restore location and reload environment in case if they were changed
Set-Location $origLocation
# [Environment]::CurrentDirectory = $origLocation ## In some future cases this line may need to be executed
Update-SessionEnvironment
# Measure taken time
$stopwatch.Stop()
$timeTaken = $stopwatch.Elapsed.ToString("dd\.hh\:mm\:ss")
Write-Host "... this step executed in $timeTaken`n"

### HACK: we disable symbolic links when cloning repositories
### to work around a symlink-related failure in the agent-binaries omnibus project
### when copying the datadog-agent project twice.
# Content: RUN git config --system core.symlinks false
$stopwatch = [system.diagnostics.stopwatch]::StartNew()
Write-Host @'
Starting to git config --system core.symlinks false
 ...
'@
git config --system core.symlinks false
# Restore location and reload environment in case if they were changed
Set-Location $origLocation
# [Environment]::CurrentDirectory = $origLocation ## In some future cases this line may need to be executed
Update-SessionEnvironment
# Measure taken time
$stopwatch.Stop()
$timeTaken = $stopwatch.Elapsed.ToString("dd\.hh\:mm\:ss")
Write-Host "... this step executed in $timeTaken`n"

# Install VS2017
# Content: COPY ./windows/install_vstudio.ps1 install_vstudio.ps1
Write-Host @'
Starting to copy $DockerRepoPath\.\windows\install_vstudio.ps1 install_vstudio.ps1 ...
'@
copy $DockerRepoPath\.\windows\install_vstudio.ps1 install_vstudio.ps1
Write-Host

# Content: RUN powershell -Command .\install_vstudio.ps1 -Version $ENV:VS2017BUILDTOOLS_VERSION -Sha256 $ENV:VS2017BUILDTOOLS_SHA256 $ENV:VS2017BUILDTOOLS_DOWNLOAD_URL
$stopwatch = [system.diagnostics.stopwatch]::StartNew()
Write-Host @'
Starting to .\install_vstudio.ps1 -Version $ENV:VS2017BUILDTOOLS_VERSION -Sha256 $ENV:VS2017BUILDTOOLS_SHA256 $ENV:VS2017BUILDTOOLS_DOWNLOAD_URL
 ...
'@
.\install_vstudio.ps1 -Version $ENV:VS2017BUILDTOOLS_VERSION -Sha256 $ENV:VS2017BUILDTOOLS_SHA256 $ENV:VS2017BUILDTOOLS_DOWNLOAD_URL
# Restore location and reload environment in case if they were changed
Set-Location $origLocation
# [Environment]::CurrentDirectory = $origLocation ## In some future cases this line may need to be executed
Update-SessionEnvironment
# Measure taken time
$stopwatch.Stop()
$timeTaken = $stopwatch.Elapsed.ToString("dd\.hh\:mm\:ss")
Write-Host "... this step executed in $timeTaken`n"

# If x64, install the WDK for driver development
# Content: COPY ./windows/install_wdk.ps1 install_wdk.ps1
Write-Host @'
Starting to copy $DockerRepoPath\.\windows\install_wdk.ps1 install_wdk.ps1 ...
'@
copy $DockerRepoPath\.\windows\install_wdk.ps1 install_wdk.ps1
Write-Host

# Content: RUN if ($Env:TARGET_ARCH -eq 'x64') { powershell -Command .\install_wdk.ps1 }
$stopwatch = [system.diagnostics.stopwatch]::StartNew()
Write-Host @'
Starting to if ($Env:TARGET_ARCH -eq 'x64') { powershell -Command .\install_wdk.ps1 }
 ...
'@
if ($Env:TARGET_ARCH -eq 'x64') { powershell -Command .\install_wdk.ps1 }
# Restore location and reload environment in case if they were changed
Set-Location $origLocation
# [Environment]::CurrentDirectory = $origLocation ## In some future cases this line may need to be executed
Update-SessionEnvironment
# Measure taken time
$stopwatch.Stop()
$timeTaken = $stopwatch.Elapsed.ToString("dd\.hh\:mm\:ss")
Write-Host "... this step executed in $timeTaken`n"

# Install Wix and update PATH to include it
# Content: COPY ./windows/install_wix.ps1 install_wix.ps1
Write-Host @'
Starting to copy $DockerRepoPath\.\windows\install_wix.ps1 install_wix.ps1 ...
'@
copy $DockerRepoPath\.\windows\install_wix.ps1 install_wix.ps1
Write-Host

# Content: RUN powershell -Command .\install_wix.ps1 -Version $ENV:WIX_VERSION -Sha256 $ENV:WIX_SHA256
$stopwatch = [system.diagnostics.stopwatch]::StartNew()
Write-Host @'
Starting to .\install_wix.ps1 -Version $ENV:WIX_VERSION -Sha256 $ENV:WIX_SHA256
 ...
'@
.\install_wix.ps1 -Version $ENV:WIX_VERSION -Sha256 $ENV:WIX_SHA256
# Restore location and reload environment in case if they were changed
Set-Location $origLocation
# [Environment]::CurrentDirectory = $origLocation ## In some future cases this line may need to be executed
Update-SessionEnvironment
# Measure taken time
$stopwatch.Stop()
$timeTaken = $stopwatch.Elapsed.ToString("dd\.hh\:mm\:ss")
Write-Host "... this step executed in $timeTaken`n"

# Install dotnet core
# Content: COPY ./windows/install_dotnetcore.ps1 install_dotnetcore.ps1
Write-Host @'
Starting to copy $DockerRepoPath\.\windows\install_dotnetcore.ps1 install_dotnetcore.ps1 ...
'@
copy $DockerRepoPath\.\windows\install_dotnetcore.ps1 install_dotnetcore.ps1
Write-Host

# Content: RUN powershell -Command .\install_dotnetcore.ps1
$stopwatch = [system.diagnostics.stopwatch]::StartNew()
Write-Host @'
Starting to .\install_dotnetcore.ps1
 ...
'@
.\install_dotnetcore.ps1
# Restore location and reload environment in case if they were changed
Set-Location $origLocation
# [Environment]::CurrentDirectory = $origLocation ## In some future cases this line may need to be executed
Update-SessionEnvironment
# Measure taken time
$stopwatch.Stop()
$timeTaken = $stopwatch.Elapsed.ToString("dd\.hh\:mm\:ss")
Write-Host "... this step executed in $timeTaken`n"

# install nuget
# Content: COPY ./windows/install_nuget.ps1 install_nuget.ps1
Write-Host @'
Starting to copy $DockerRepoPath\.\windows\install_nuget.ps1 install_nuget.ps1 ...
'@
copy $DockerRepoPath\.\windows\install_nuget.ps1 install_nuget.ps1
Write-Host

# Content: RUN powershell -Command .\install_nuget.ps1 -Version $ENV:NUGET_VERSION -Sha256 $ENV:NUGET_SHA256
$stopwatch = [system.diagnostics.stopwatch]::StartNew()
Write-Host @'
Starting to .\install_nuget.ps1 -Version $ENV:NUGET_VERSION -Sha256 $ENV:NUGET_SHA256
 ...
'@
.\install_nuget.ps1 -Version $ENV:NUGET_VERSION -Sha256 $ENV:NUGET_SHA256
# Restore location and reload environment in case if they were changed
Set-Location $origLocation
# [Environment]::CurrentDirectory = $origLocation ## In some future cases this line may need to be executed
Update-SessionEnvironment
# Measure taken time
$stopwatch.Stop()
$timeTaken = $stopwatch.Elapsed.ToString("dd\.hh\:mm\:ss")
Write-Host "... this step executed in $timeTaken`n"

# Install VC compiler for Python 2.7
# Content: COPY ./windows/install_vcpython.ps1 install_vcpython.ps1
Write-Host @'
Starting to copy $DockerRepoPath\.\windows\install_vcpython.ps1 install_vcpython.ps1 ...
'@
copy $DockerRepoPath\.\windows\install_vcpython.ps1 install_vcpython.ps1
Write-Host

# Content: RUN powershell -Command .\install_vcpython.ps1
$stopwatch = [system.diagnostics.stopwatch]::StartNew()
Write-Host @'
Starting to .\install_vcpython.ps1
 ...
'@
.\install_vcpython.ps1
# Restore location and reload environment in case if they were changed
Set-Location $origLocation
# [Environment]::CurrentDirectory = $origLocation ## In some future cases this line may need to be executed
Update-SessionEnvironment
# Measure taken time
$stopwatch.Stop()
$timeTaken = $stopwatch.Elapsed.ToString("dd\.hh\:mm\:ss")
Write-Host "... this step executed in $timeTaken`n"

# Install IBM MQ
# Content: COPY ./windows/install_ibm_mq.ps1 install_ibm_mq.ps1
Write-Host @'
Starting to copy $DockerRepoPath\.\windows\install_ibm_mq.ps1 install_ibm_mq.ps1 ...
'@
copy $DockerRepoPath\.\windows\install_ibm_mq.ps1 install_ibm_mq.ps1
Write-Host

# Content: RUN Powershell -C .\install_ibm_mq.ps1 -Version $ENV:IBM_MQ_VERSION -Sha256 $ENV:IBM_MQ_SHA256
$stopwatch = [system.diagnostics.stopwatch]::StartNew()
Write-Host @'
Starting to .\install_ibm_mq.ps1 -Version $ENV:IBM_MQ_VERSION -Sha256 $ENV:IBM_MQ_SHA256
 ...
'@
.\install_ibm_mq.ps1 -Version $ENV:IBM_MQ_VERSION -Sha256 $ENV:IBM_MQ_SHA256
# Restore location and reload environment in case if they were changed
Set-Location $origLocation
# [Environment]::CurrentDirectory = $origLocation ## In some future cases this line may need to be executed
Update-SessionEnvironment
# Measure taken time
$stopwatch.Stop()
$timeTaken = $stopwatch.Elapsed.ToString("dd\.hh\:mm\:ss")
Write-Host "... this step executed in $timeTaken`n"

# Content: RUN setx MQ_FILE_PATH c:\ibm_mq
$stopwatch = [system.diagnostics.stopwatch]::StartNew()
Write-Host @'
Starting to setx MQ_FILE_PATH c:\ibm_mq
 ...
'@
setx MQ_FILE_PATH c:\ibm_mq
# Restore location and reload environment in case if they were changed
Set-Location $origLocation
# [Environment]::CurrentDirectory = $origLocation ## In some future cases this line may need to be executed
Update-SessionEnvironment
# Measure taken time
$stopwatch.Stop()
$timeTaken = $stopwatch.Elapsed.ToString("dd\.hh\:mm\:ss")
Write-Host "... this step executed in $timeTaken`n"

# Install Cmake and update PATH to include it
# Content: COPY ./windows/install_cmake.ps1 install_cmake.ps1
Write-Host @'
Starting to copy $DockerRepoPath\.\windows\install_cmake.ps1 install_cmake.ps1 ...
'@
copy $DockerRepoPath\.\windows\install_cmake.ps1 install_cmake.ps1
Write-Host

# Content: RUN powershell -Command .\install_cmake.ps1 -Version $ENV:CMAKE_VERSION -Sha256 $ENV:CMAKE_SHA256
$stopwatch = [system.diagnostics.stopwatch]::StartNew()
Write-Host @'
Starting to .\install_cmake.ps1 -Version $ENV:CMAKE_VERSION -Sha256 $ENV:CMAKE_SHA256
 ...
'@
.\install_cmake.ps1 -Version $ENV:CMAKE_VERSION -Sha256 $ENV:CMAKE_SHA256
# Restore location and reload environment in case if they were changed
Set-Location $origLocation
# [Environment]::CurrentDirectory = $origLocation ## In some future cases this line may need to be executed
Update-SessionEnvironment
# Measure taken time
$stopwatch.Stop()
$timeTaken = $stopwatch.Elapsed.ToString("dd\.hh\:mm\:ss")
Write-Host "... this step executed in $timeTaken`n"

# Install Winget and update PATH to include it
# Content: COPY ./windows/install_winget.ps1 install_winget.ps1
Write-Host @'
Starting to copy $DockerRepoPath\.\windows\install_winget.ps1 install_winget.ps1 ...
'@
copy $DockerRepoPath\.\windows\install_winget.ps1 install_winget.ps1
Write-Host

# Content: RUN powershell -Command .\install_winget.ps1 -Version $ENV:WINGET_VERSION -Sha256 $ENV:WINGET_SHA256
$stopwatch = [system.diagnostics.stopwatch]::StartNew()
Write-Host @'
Starting to .\install_winget.ps1 -Version $ENV:WINGET_VERSION -Sha256 $ENV:WINGET_SHA256
 ...
'@
.\install_winget.ps1 -Version $ENV:WINGET_VERSION -Sha256 $ENV:WINGET_SHA256
# Restore location and reload environment in case if they were changed
Set-Location $origLocation
# [Environment]::CurrentDirectory = $origLocation ## In some future cases this line may need to be executed
Update-SessionEnvironment
# Measure taken time
$stopwatch.Stop()
$timeTaken = $stopwatch.Elapsed.ToString("dd\.hh\:mm\:ss")
Write-Host "... this step executed in $timeTaken`n"

# Install golang and set GOPATH to the dev path used in builds & tests
# RUN cinst -y --no-progress golang $ENV:CHOCO_ARCH_FLAG --version $ENV:GO_VERSION
# Some go point releases are not available as chocolatey packages, we have to install them directly
# Content: COPY ./windows/install_go.ps1 install_go.ps1
Write-Host @'
Starting to copy $DockerRepoPath\.\windows\install_go.ps1 install_go.ps1 ...
'@
copy $DockerRepoPath\.\windows\install_go.ps1 install_go.ps1
Write-Host

# Content: RUN powershell -C .\install_go.ps1
$stopwatch = [system.diagnostics.stopwatch]::StartNew()
Write-Host @'
Starting to .\install_go.ps1
 ...
'@
.\install_go.ps1
# Restore location and reload environment in case if they were changed
Set-Location $origLocation
# [Environment]::CurrentDirectory = $origLocation ## In some future cases this line may need to be executed
Update-SessionEnvironment
# Measure taken time
$stopwatch.Stop()
$timeTaken = $stopwatch.Elapsed.ToString("dd\.hh\:mm\:ss")
Write-Host "... this step executed in $timeTaken`n"

# Content: RUN setx GOPATH C:\dev\go
$stopwatch = [system.diagnostics.stopwatch]::StartNew()
Write-Host @'
Starting to setx GOPATH C:\dev\go
 ...
'@
setx GOPATH C:\dev\go
# Restore location and reload environment in case if they were changed
Set-Location $origLocation
# [Environment]::CurrentDirectory = $origLocation ## In some future cases this line may need to be executed
Update-SessionEnvironment
# Measure taken time
$stopwatch.Stop()
$timeTaken = $stopwatch.Elapsed.ToString("dd\.hh\:mm\:ss")
Write-Host "... this step executed in $timeTaken`n"

# Install system Python 3 (to use invoke).
# We always install the 64 bit version because vcredist140 won't work otherwise
# Content: COPY ./windows/install_python.ps1 install_python.ps1
Write-Host @'
Starting to copy $DockerRepoPath\.\windows\install_python.ps1 install_python.ps1 ...
'@
copy $DockerRepoPath\.\windows\install_python.ps1 install_python.ps1
Write-Host

# Content: COPY ./requirements.txt ./requirements-py2.txt /
Write-Host @'
Starting to copy $DockerRepoPath\.\requirements.txt \ ...
'@
copy $DockerRepoPath\.\requirements.txt \
Write-Host @'
Starting to copy $DockerRepoPath\.\requirements-py2.txt \ ...
'@
copy $DockerRepoPath\.\requirements-py2.txt \
Write-Host

# Content: RUN powershell -C .\install_python.ps1 -Version $ENV:PYTHON_VERSION -Sha256 $ENV:PYTHON_SHA256
$stopwatch = [system.diagnostics.stopwatch]::StartNew()
Write-Host @'
Starting to .\install_python.ps1 -Version $ENV:PYTHON_VERSION -Sha256 $ENV:PYTHON_SHA256
 ...
'@
.\install_python.ps1 -Version $ENV:PYTHON_VERSION -Sha256 $ENV:PYTHON_SHA256
# Restore location and reload environment in case if they were changed
Set-Location $origLocation
# [Environment]::CurrentDirectory = $origLocation ## In some future cases this line may need to be executed
Update-SessionEnvironment
# Measure taken time
$stopwatch.Stop()
$timeTaken = $stopwatch.Elapsed.ToString("dd\.hh\:mm\:ss")
Write-Host "... this step executed in $timeTaken`n"

# Install 64-bit ruby and bundler (for omnibus builds)
# Content: COPY ./windows/install_ruby.ps1 install_ruby.ps1
Write-Host @'
Starting to copy $DockerRepoPath\.\windows\install_ruby.ps1 install_ruby.ps1 ...
'@
copy $DockerRepoPath\.\windows\install_ruby.ps1 install_ruby.ps1
Write-Host

# Content: RUN powershell -C .\install_ruby.ps1 -Version $ENV:RUBY_VERSION -Sha256 $ENV:RUBY_SHA256
$stopwatch = [system.diagnostics.stopwatch]::StartNew()
Write-Host @'
Starting to .\install_ruby.ps1 -Version $ENV:RUBY_VERSION -Sha256 $ENV:RUBY_SHA256
 ...
'@
.\install_ruby.ps1 -Version $ENV:RUBY_VERSION -Sha256 $ENV:RUBY_SHA256
# Restore location and reload environment in case if they were changed
Set-Location $origLocation
# [Environment]::CurrentDirectory = $origLocation ## In some future cases this line may need to be executed
Update-SessionEnvironment
# Measure taken time
$stopwatch.Stop()
$timeTaken = $stopwatch.Elapsed.ToString("dd\.hh\:mm\:ss")
Write-Host "... this step executed in $timeTaken`n"

# Install msys2 system & install 64-bit C/C++ compilation toolchain
# Content: copy ./windows/install_msys.ps1 install_msys.ps1
Write-Host @'
Starting to copy $DockerRepoPath\.\windows\install_msys.ps1 install_msys.ps1 ...
'@
copy $DockerRepoPath\.\windows\install_msys.ps1 install_msys.ps1
Write-Host

# Content: RUN powershell -C .\install_msys.ps1 -Version $ENV:MSYS_VERSION -Sha256 $ENV:MSYS_SHA256
$stopwatch = [system.diagnostics.stopwatch]::StartNew()
Write-Host @'
Starting to .\install_msys.ps1 -Version $ENV:MSYS_VERSION -Sha256 $ENV:MSYS_SHA256
 ...
'@
.\install_msys.ps1 -Version $ENV:MSYS_VERSION -Sha256 $ENV:MSYS_SHA256
# Restore location and reload environment in case if they were changed
Set-Location $origLocation
# [Environment]::CurrentDirectory = $origLocation ## In some future cases this line may need to be executed
Update-SessionEnvironment
# Measure taken time
$stopwatch.Stop()
$timeTaken = $stopwatch.Elapsed.ToString("dd\.hh\:mm\:ss")
Write-Host "... this step executed in $timeTaken`n"

# Content: RUN ridk install 3
$stopwatch = [system.diagnostics.stopwatch]::StartNew()
Write-Host @'
Starting to ridk install 3
 ...
'@
ridk install 3
# Restore location and reload environment in case if they were changed
Set-Location $origLocation
# [Environment]::CurrentDirectory = $origLocation ## In some future cases this line may need to be executed
Update-SessionEnvironment
# Measure taken time
$stopwatch.Stop()
$timeTaken = $stopwatch.Elapsed.ToString("dd\.hh\:mm\:ss")
Write-Host "... this step executed in $timeTaken`n"

# Downgrade gcc and binutils due to https://github.com/golang/go/issues/46099
# Content: RUN (New-Object System.Net.WebClient).DownloadFile(\"https://s3.amazonaws.com/dd-agent-omnibus/mingw-w64-x86_64-gcc-10.2.0-11-any.pkg.tar.zst\", \"C:/mingw-w64-x86_64-gcc-10.2.0-11-any.pkg.tar.zst\")
$stopwatch = [system.diagnostics.stopwatch]::StartNew()
Write-Host @'
Starting to (New-Object System.Net.WebClient).DownloadFile("https://s3.amazonaws.com/dd-agent-omnibus/mingw-w64-x86_64-gcc-10.2.0-11-any.pkg.tar.zst", "C:/mingw-w64-x86_64-gcc-10.2.0-11-any.pkg.tar.zst")
 ...
'@
(New-Object System.Net.WebClient).DownloadFile("https://s3.amazonaws.com/dd-agent-omnibus/mingw-w64-x86_64-gcc-10.2.0-11-any.pkg.tar.zst", "C:/mingw-w64-x86_64-gcc-10.2.0-11-any.pkg.tar.zst")
# Restore location and reload environment in case if they were changed
Set-Location $origLocation
# [Environment]::CurrentDirectory = $origLocation ## In some future cases this line may need to be executed
Update-SessionEnvironment
# Measure taken time
$stopwatch.Stop()
$timeTaken = $stopwatch.Elapsed.ToString("dd\.hh\:mm\:ss")
Write-Host "... this step executed in $timeTaken`n"

# Content: RUN (New-Object System.Net.WebClient).DownloadFile(\"https://s3.amazonaws.com/dd-agent-omnibus/mingw-w64-x86_64-gcc-libs-10.2.0-11-any.pkg.tar.zst\", \"C:/mingw-w64-x86_64-gcc-libs-10.2.0-11-any.pkg.tar.zst\")
$stopwatch = [system.diagnostics.stopwatch]::StartNew()
Write-Host @'
Starting to (New-Object System.Net.WebClient).DownloadFile("https://s3.amazonaws.com/dd-agent-omnibus/mingw-w64-x86_64-gcc-libs-10.2.0-11-any.pkg.tar.zst", "C:/mingw-w64-x86_64-gcc-libs-10.2.0-11-any.pkg.tar.zst")
 ...
'@
(New-Object System.Net.WebClient).DownloadFile("https://s3.amazonaws.com/dd-agent-omnibus/mingw-w64-x86_64-gcc-libs-10.2.0-11-any.pkg.tar.zst", "C:/mingw-w64-x86_64-gcc-libs-10.2.0-11-any.pkg.tar.zst")
# Restore location and reload environment in case if they were changed
Set-Location $origLocation
# [Environment]::CurrentDirectory = $origLocation ## In some future cases this line may need to be executed
Update-SessionEnvironment
# Measure taken time
$stopwatch.Stop()
$timeTaken = $stopwatch.Elapsed.ToString("dd\.hh\:mm\:ss")
Write-Host "... this step executed in $timeTaken`n"

# Content: RUN (New-Object System.Net.WebClient).DownloadFile(\"https://s3.amazonaws.com/dd-agent-omnibus/mingw-w64-x86_64-binutils-2.35.1-2-any.pkg.tar.zst\", \"C:/mingw-w64-x86_64-binutils-2.35.1-2-any.pkg.tar.zst\")
$stopwatch = [system.diagnostics.stopwatch]::StartNew()
Write-Host @'
Starting to (New-Object System.Net.WebClient).DownloadFile("https://s3.amazonaws.com/dd-agent-omnibus/mingw-w64-x86_64-binutils-2.35.1-2-any.pkg.tar.zst", "C:/mingw-w64-x86_64-binutils-2.35.1-2-any.pkg.tar.zst")
 ...
'@
(New-Object System.Net.WebClient).DownloadFile("https://s3.amazonaws.com/dd-agent-omnibus/mingw-w64-x86_64-binutils-2.35.1-2-any.pkg.tar.zst", "C:/mingw-w64-x86_64-binutils-2.35.1-2-any.pkg.tar.zst")
# Restore location and reload environment in case if they were changed
Set-Location $origLocation
# [Environment]::CurrentDirectory = $origLocation ## In some future cases this line may need to be executed
Update-SessionEnvironment
# Measure taken time
$stopwatch.Stop()
$timeTaken = $stopwatch.Elapsed.ToString("dd\.hh\:mm\:ss")
Write-Host "... this step executed in $timeTaken`n"

# Content: RUN C:\tools\msys64\msys2_shell.cmd -defterm -no-start -c \"pacman --noconfirm -U /c/mingw-w64-x86_64-binutils-2.35.1-2-any.pkg.tar.zst /c/mingw-w64-x86_64-gcc-libs-10.2.0-11-any.pkg.tar.zst /c/mingw-w64-x86_64-gcc-10.2.0-11-any.pkg.tar.zst\"
$stopwatch = [system.diagnostics.stopwatch]::StartNew()
Write-Host @'
Starting to C:\tools\msys64\msys2_shell.cmd -defterm -no-start -c "pacman --noconfirm -U /c/mingw-w64-x86_64-binutils-2.35.1-2-any.pkg.tar.zst /c/mingw-w64-x86_64-gcc-libs-10.2.0-11-any.pkg.tar.zst /c/mingw-w64-x86_64-gcc-10.2.0-11-any.pkg.tar.zst"
 ...
'@
C:\tools\msys64\msys2_shell.cmd -defterm -no-start -c "pacman --noconfirm -U /c/mingw-w64-x86_64-binutils-2.35.1-2-any.pkg.tar.zst /c/mingw-w64-x86_64-gcc-libs-10.2.0-11-any.pkg.tar.zst /c/mingw-w64-x86_64-gcc-10.2.0-11-any.pkg.tar.zst"
# Restore location and reload environment in case if they were changed
Set-Location $origLocation
# [Environment]::CurrentDirectory = $origLocation ## In some future cases this line may need to be executed
Update-SessionEnvironment
# Measure taken time
$stopwatch.Stop()
$timeTaken = $stopwatch.Elapsed.ToString("dd\.hh\:mm\:ss")
Write-Host "... this step executed in $timeTaken`n"

# Install docker, manifest-tool and notary
# Content: COPY ./windows/install_docker.ps1 install_docker.ps1
Write-Host @'
Starting to copy $DockerRepoPath\.\windows\install_docker.ps1 install_docker.ps1 ...
'@
copy $DockerRepoPath\.\windows\install_docker.ps1 install_docker.ps1
Write-Host

# Content: RUN powershell -Command .\install_docker.ps1
$stopwatch = [system.diagnostics.stopwatch]::StartNew()
Write-Host @'
Starting to .\install_docker.ps1
 ...
'@
.\install_docker.ps1
# Restore location and reload environment in case if they were changed
Set-Location $origLocation
# [Environment]::CurrentDirectory = $origLocation ## In some future cases this line may need to be executed
Update-SessionEnvironment
# Measure taken time
$stopwatch.Stop()
$timeTaken = $stopwatch.Elapsed.ToString("dd\.hh\:mm\:ss")
Write-Host "... this step executed in $timeTaken`n"

# Install google cloud SDK
# Content: COPY ./windows/install_gcloud_sdk.ps1 install_gcloud_sdk.ps1
Write-Host @'
Starting to copy $DockerRepoPath\.\windows\install_gcloud_sdk.ps1 install_gcloud_sdk.ps1 ...
'@
copy $DockerRepoPath\.\windows\install_gcloud_sdk.ps1 install_gcloud_sdk.ps1
Write-Host

# Content: RUN powershell -C .\install_gcloud_sdk.ps1
$stopwatch = [system.diagnostics.stopwatch]::StartNew()
Write-Host @'
Starting to .\install_gcloud_sdk.ps1
 ...
'@
.\install_gcloud_sdk.ps1
# Restore location and reload environment in case if they were changed
Set-Location $origLocation
# [Environment]::CurrentDirectory = $origLocation ## In some future cases this line may need to be executed
Update-SessionEnvironment
# Measure taken time
$stopwatch.Stop()
$timeTaken = $stopwatch.Elapsed.ToString("dd\.hh\:mm\:ss")
Write-Host "... this step executed in $timeTaken`n"

# Install embedded pythons (for unit testing)
# Content: COPY ./python-packages-versions.txt python-packages-versions.txt
Write-Host @'
Starting to copy $DockerRepoPath\.\python-packages-versions.txt python-packages-versions.txt ...
'@
copy $DockerRepoPath\.\python-packages-versions.txt python-packages-versions.txt
Write-Host

# Content: COPY ./windows/install_embedded_pythons.ps1 install_embedded_pythons.ps1
Write-Host @'
Starting to copy $DockerRepoPath\.\windows\install_embedded_pythons.ps1 install_embedded_pythons.ps1 ...
'@
copy $DockerRepoPath\.\windows\install_embedded_pythons.ps1 install_embedded_pythons.ps1
Write-Host

# Content: RUN powershell -C .\install_embedded_pythons.ps1
$stopwatch = [system.diagnostics.stopwatch]::StartNew()
Write-Host @'
Starting to .\install_embedded_pythons.ps1
 ...
'@
.\install_embedded_pythons.ps1
# Restore location and reload environment in case if they were changed
Set-Location $origLocation
# [Environment]::CurrentDirectory = $origLocation ## In some future cases this line may need to be executed
Update-SessionEnvironment
# Measure taken time
$stopwatch.Stop()
$timeTaken = $stopwatch.Elapsed.ToString("dd\.hh\:mm\:ss")
Write-Host "... this step executed in $timeTaken`n"

# install vcpkg
# Content: COPY ./windows/install_vcpkg.ps1 install_vcpkg.ps1
Write-Host @'
Starting to copy $DockerRepoPath\.\windows\install_vcpkg.ps1 install_vcpkg.ps1 ...
'@
copy $DockerRepoPath\.\windows\install_vcpkg.ps1 install_vcpkg.ps1
Write-Host

# Content: RUN powershell -Command .\install_vcpkg.ps1
$stopwatch = [system.diagnostics.stopwatch]::StartNew()
Write-Host @'
Starting to .\install_vcpkg.ps1
 ...
'@
.\install_vcpkg.ps1
# Restore location and reload environment in case if they were changed
Set-Location $origLocation
# [Environment]::CurrentDirectory = $origLocation ## In some future cases this line may need to be executed
Update-SessionEnvironment
# Measure taken time
$stopwatch.Stop()
$timeTaken = $stopwatch.Elapsed.ToString("dd\.hh\:mm\:ss")
Write-Host "... this step executed in $timeTaken`n"

# Add signtool to path
# Content: RUN [Environment]::SetEnvironmentVariable(\"Path\", [Environment]::GetEnvironmentVariable(\"Path\", [EnvironmentVariableTarget]::Machine) + \";${env:ProgramFiles(x86)}\Windows Kits\8.1\bin\x64\", [System.EnvironmentVariableTarget]::Machine)
$stopwatch = [system.diagnostics.stopwatch]::StartNew()
Write-Host @'
Starting to [Environment]::SetEnvironmentVariable("Path", [Environment]::GetEnvironmentVariable("Path", [EnvironmentVariableTarget]::Machine) + ";${env:ProgramFiles(x86)}\Windows Kits\8.1\bin\x64", [System.EnvironmentVariableTarget]::Machine)
 ...
'@
[Environment]::SetEnvironmentVariable("Path", [Environment]::GetEnvironmentVariable("Path", [EnvironmentVariableTarget]::Machine) + ";${env:ProgramFiles(x86)}\Windows Kits\8.1\bin\x64", [System.EnvironmentVariableTarget]::Machine)
# Restore location and reload environment in case if they were changed
Set-Location $origLocation
# [Environment]::CurrentDirectory = $origLocation ## In some future cases this line may need to be executed
Update-SessionEnvironment
# Measure taken time
$stopwatch.Stop()
$timeTaken = $stopwatch.Elapsed.ToString("dd\.hh\:mm\:ss")
Write-Host "... this step executed in $timeTaken`n"

# Set 32-bit flag env var
# Content: RUN if ($Env:TARGET_ARCH -eq 'x86') { setx WINDOWS_BUILD_32_BIT 1 }
$stopwatch = [system.diagnostics.stopwatch]::StartNew()
Write-Host @'
Starting to if ($Env:TARGET_ARCH -eq 'x86') { setx WINDOWS_BUILD_32_BIT 1 }
 ...
'@
if ($Env:TARGET_ARCH -eq 'x86') { setx WINDOWS_BUILD_32_BIT 1 }
# Restore location and reload environment in case if they were changed
Set-Location $origLocation
# [Environment]::CurrentDirectory = $origLocation ## In some future cases this line may need to be executed
Update-SessionEnvironment
# Measure taken time
$stopwatch.Stop()
$timeTaken = $stopwatch.Elapsed.ToString("dd\.hh\:mm\:ss")
Write-Host "... this step executed in $timeTaken`n"

# Content: COPY ./windows/set_cpython_compiler.cmd set_cpython_compiler.cmd
Write-Host @'
Starting to copy $DockerRepoPath\.\windows\set_cpython_compiler.cmd set_cpython_compiler.cmd ...
'@
copy $DockerRepoPath\.\windows\set_cpython_compiler.cmd set_cpython_compiler.cmd
Write-Host

# Content: RUN .\set_cpython_compiler.cmd
$stopwatch = [system.diagnostics.stopwatch]::StartNew()
Write-Host @'
Starting to .\set_cpython_compiler.cmd
 ...
'@
.\set_cpython_compiler.cmd
# Restore location and reload environment in case if they were changed
Set-Location $origLocation
# [Environment]::CurrentDirectory = $origLocation ## In some future cases this line may need to be executed
Update-SessionEnvironment
# Measure taken time
$stopwatch.Stop()
$timeTaken = $stopwatch.Elapsed.ToString("dd\.hh\:mm\:ss")
Write-Host "... this step executed in $timeTaken`n"

# Content: COPY ./windows/entrypoint.bat /entrypoint.bat
Write-Host @'
Starting to copy $DockerRepoPath\.\windows\entrypoint.bat \entrypoint.bat ...
'@
copy $DockerRepoPath\.\windows\entrypoint.bat \entrypoint.bat
Write-Host

# Content: COPY ./windows/aws_networking.ps1 /aws_networking.ps1
Write-Host @'
Starting to copy $DockerRepoPath\.\windows\aws_networking.ps1 \aws_networking.ps1 ...
'@
copy $DockerRepoPath\.\windows\aws_networking.ps1 \aws_networking.ps1
Write-Host

# Content: ENTRYPOINT ["/entrypoint.bat"]


$totalStopwatch.Stop()
$timeTaken = $totalStopwatch.Elapsed.ToString("dd\.hh\:mm\:ss")
Write-Host "Script executed in $timeTaken"
