---
version: 2
updates:
  - package-ecosystem: pip
    directory: /
    labels:
      - dependencies
      - python
    schedule:
      interval: monthly
    ignore:
      # pyyaml 6 is incompatible with awscli
      # see https://github.com/DataDog/datadog-agent-buildimages/pull/207
      - dependency-name: pyyaml
  - package-ecosystem: github-actions
    directory: /
    labels:
      - dependencies
    schedule:
      interval: monthly
