---
.x64:
  tags: ["arch:amd64"]
  image: $BUILDENV_REGISTRY/images/docker:27.3.1
  variables:
    ARCH: x86_64
    DD_TARGET_ARCH: x64
    PLATFORM: linux/amd64

.arm:
  tags: ["arch:arm64"]
  image: $BUILDENV_REGISTRY/images/docker:27.3.1
  variables:
    ARCH: aarch64
    DD_TARGET_ARCH: aarch64
    PLATFORM: linux/arm64

.always:
  rules:
    - if: $CI_COMMIT_TAG == null

.no_schedule:
  rules:
    - if: $CI_COMMIT_TAG == null && $CI_PIPELINE_SOURCE != "schedule"
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never

.build:
  stage: build
  before_script:
    - curl "https://awscli.amazonaws.com/awscli-exe-linux-$ARCH.zip" -o "awscliv2.zip"
    - unzip awscliv2.zip
    - ./aws/install
    # Docker Hub login to reduce risk of rate limiting.
    - DOCKER_REGISTRY_LOGIN=$(aws ssm get-parameter --region us-east-1 --name ci.datadog-agent.docker_hub_login --with-decryption --query "Parameter.Value" --out text)
    - aws ssm get-parameter --region us-east-1 --name ci.datadog-agent.docker_hub_pwd --with-decryption --query "Parameter.Value" --out text | docker login --username "$DOCKER_REGISTRY_LOGIN" --password-stdin docker.io
  script:
    - ./build.sh
  artifacts:
    paths: ["./$IMAGE-$IMAGE_VERSION.tar"]
    expire_in: 1 hour
  retry: 1 # Add a retry to prevent flakyness on build stage.

build_x64:
  extends: [.build, .always, .x64]
  parallel:
    matrix:
      - DOCKERFILE: deb-x64/Dockerfile
        IMAGE: deb_x64
      - DOCKERFILE: rpm-x64/Dockerfile
        IMAGE: rpm_x64
        BASE_IMAGE: centos:7
      - DOCKERFILE: dd-agent-testing/Dockerfile
        IMAGE: dd-agent-testing
      - DOCKERFILE: docker-x64/Dockerfile
        IMAGE: docker_x64
      - DOCKERFILE: btf-gen/Dockerfile
        IMAGE: btf-gen
      - CUSTOM_BUILD_ARGS: --build-arg KERNEL_EXTRA_CONFIG_VERSION=$EXTRA_KCONFIG_VERSION
        DOCKERFILE: kernel-version-testing/kernel-version-testing_x64/Dockerfile
        IMAGE: kernel-version-testing_x64
      - DOCKERFILE: agent-deploy/Dockerfile
        IMAGE: gitlab_agent_deploy
      - DOCKERFILE: linux/Dockerfile
        IMAGE: linux
        IMAGE_VERSION: v$CI_PIPELINE_ID-${CI_COMMIT_SHORT_SHA}-x64
        BUILD_ARGS_FILE: linux/x64/build.env

build_arm64:
  extends: [.build, .always, .arm]
  parallel:
    matrix:
      - DOCKERFILE: deb-arm/Dockerfile
        IMAGE: deb_arm64
        BASE_IMAGE: arm64v8/ubuntu:16.04
      - DOCKERFILE: deb-arm/Dockerfile
        IMAGE: deb_armhf
        BASE_IMAGE: arm32v7/ubuntu:16.04
        DD_TARGET_ARCH: armhf
      - DOCKERFILE: rpm-arm64/Dockerfile
        IMAGE: rpm_arm64
        BASE_IMAGE: amazonlinux:2.0.20181114
      - DOCKERFILE: rpm-armhf/Dockerfile
        IMAGE: rpm_armhf
        BASE_IMAGE: arm32v7/centos:7
        DD_TARGET_ARCH: armhf
      - DOCKERFILE: docker-arm64/Dockerfile
        IMAGE: docker_arm64
      - CUSTOM_BUILD_ARGS: --build-arg KERNEL_EXTRA_CONFIG_VERSION=$EXTRA_KCONFIG_VERSION
        DOCKERFILE: kernel-version-testing/kernel-version-testing_arm64/Dockerfile
        IMAGE: kernel-version-testing_arm64
      - DOCKERFILE: linux/Dockerfile
        IMAGE: linux
        IMAGE_VERSION: v$CI_PIPELINE_ID-${CI_COMMIT_SHORT_SHA}-arm64
        BUILD_ARGS_FILE: linux/arm64/build.env

build_multiarch:
  extends: [.always, .x64]
  stage: build
  needs:
    - job: build_x64
      parallel:
        matrix:
          - DOCKERFILE: linux/Dockerfile
            IMAGE: linux
            IMAGE_VERSION: v$CI_PIPELINE_ID-${CI_COMMIT_SHORT_SHA}-x64
            BUILD_ARGS_FILE: linux/x64/build.env
    - job: build_arm64
      parallel:
        matrix:
          - DOCKERFILE: linux/Dockerfile
            IMAGE: linux
            IMAGE_VERSION: v$CI_PIPELINE_ID-${CI_COMMIT_SHORT_SHA}-arm64
            BUILD_ARGS_FILE: linux/arm64/build.env
  variables:
    TARGET_IMAGE: registry.ddbuild.io/ci/datadog-agent-buildimages/linux$ECR_TEST_ONLY
  before_script:
    - !reference [.build, before_script]
  script:
    - >
      docker manifest create $TARGET_IMAGE:$IMAGE_VERSION
      $TARGET_IMAGE:$IMAGE_VERSION-x64
      $TARGET_IMAGE:$IMAGE_VERSION-arm64
    - docker manifest push $TARGET_IMAGE:$IMAGE_VERSION

build_dev_env_linux_x64:
  extends: [.build, .no_schedule, .x64]
  needs:
    - job: build_multiarch
  variables:
    DOCKERFILE: dev-envs/linux/Dockerfile
    IMAGE: dev-env-linux-$DD_TARGET_ARCH
    BASE_IMAGE: registry.ddbuild.io/ci/datadog-agent-buildimages/linux$ECR_TEST_ONLY
    BASE_IMAGE_TAG: $IMAGE_VERSION

build_dev_env_linux_arm64:
  extends: [.build, .no_schedule, .arm]
  needs:
    - job: build_multiarch
  variables:
    DOCKERFILE: dev-envs/linux/Dockerfile
    IMAGE: dev-env-linux-$DD_TARGET_ARCH
    BASE_IMAGE: registry.ddbuild.io/ci/datadog-agent-buildimages/linux$ECR_TEST_ONLY
    BASE_IMAGE_TAG: $IMAGE_VERSION

build_windows_ltsc2022_x64:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: on_success
    - if: $CI_COMMIT_TAG == null
      changes:
        paths:
          - build-container.ps1
          - windows/**/*
          - go.env
        compare_to: $COMPARE_TO_BRANCH
  timeout: 2h 30m
  tags: ["windows-v2:2022"]
  id_tokens:
    CI_IDENTITY_GITLAB_JWT:
      aud: https://vault.us1.ddbuild.io
  variables:
    CI_IDENTITY_ROLE_NAME_OVERRIDE: windows-ci-tmp-gitlab-id-token-datadog-agent-buildimages-all-refs
    DOCKERFILE: windows/Dockerfile
    IMAGE: windows_ltsc2022_x64
    DD_TARGET_ARCH: x64
  script:
    - '$_instance_id = (iwr  -UseBasicParsing http://169.254.169.254/latest/meta-data/instance-id).content ; Write-Host "Running on instance $($_instance_id)"'
    - $SRC_IMAGE = "registry.ddbuild.io/ci/datadog-agent-buildimages/${IMAGE}${ECR_TEST_ONLY}"
    - .\build-container.ps1 -Image $SRC_IMAGE -Tag $IMAGE_VERSION -Buildkit
    - New-Item -ItemType File -Path "windows.image" -Force # Create a file to indicate that the image is built
  artifacts:
    paths: ["./windows.image"]
    expire_in: 1 hour
