source 'https://rubygems.org'

gem "berkshelf", '~> 7.0.8'
gem "chef", '~> 15.3.4'
gem "chef-dk", '~> 4.3.13'
gem "rake", '~> 12.3.2'

group :development do
  gem "guard", '~> 2.15.0'
  gem "guard-foodcritic", '~> 3.0.0'
  gem "guard-rspec", '~> 4.7.3'
end

group :test do
  gem "tailor", '~> 1.4.1' # Ruby style
  gem "foodcritic", '~> 15.1.0' # Lint testing
end

group :azure do
  gem "kitchen-azurerm", '~> 1.10.5'
end

group :ec2 do
  gem "kitchen-ec2", '~> 3.13.0'
end

group :kitchen do
  gem "test-kitchen", '~> 3.3.1'
end
