source 'https://rubygems.org'

gem "berkshelf", '~> 7.2.2'
gem "chef", '~> 17.10.0'
gem "rake", '~> 13.0.6'

group :development do
  gem "guard", '~> 2.18.0'
  gem "guard-foodcritic", '~> 3.0.0'
  gem "guard-rspec", '~> 4.7.3'
end

group :test do
  gem "tailor", '~> 1.4.1' # Ruby style
  gem "foodcritic", '~> 16.3.0' # Lint testing
end

group :azure do
  gem "kitchen-azurerm", '~> 1.10.5'
end

group :ec2 do
  gem "kitchen-ec2", '~> 3.12.0'
end

group :kitchen do
  gem "test-kitchen", '~> 3.2.2'
end
