diff --git a/src/Makefile b/src/Makefile
index b83bf5a..1b4da25 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -169,9 +169,11 @@ else
 endif
 ifeq ($(filter -DHAVE_LLVM_SUPPORT -DHAVE_LIBBFD_SUPPORT,$(CFLAGS)),)
   # No support for JIT disassembly
-  SRCS := $(filter-out jit_disasm.c,$(SRCS))
+  FILTER_JIT = jit_disasm.c
 endif
 
+SRCS := $(filter-out $(FILTER_JIT) pids.c,$(SRCS))
+
 HOST_CFLAGS = $(subst -I$(LIBBPF_INCLUDE),-I$(LIBBPF_BOOTSTRAP_INCLUDE),\
 		$(subst $(CLANG_CROSS_FLAGS),,$(CFLAGS)))
 
