issuer: https://token.actions.githubusercontent.com

subject: repo:DataDog/datadog-agent-buildimages:ref:refs/heads/(main|7\.[0-9]+\.x)

claim_pattern:
  event_name: workflow_dispatch
  ref: refs/heads/(main|7\.[0-9]+\.x)
  ref_protected: "true"
  job_workflow_ref: DataDog/datadog-agent-buildimages/\.github/workflows/go-update\.yml@refs/heads/(main|7\.[0-9]+\.x)

permissions:
  contents: write
  pull_requests: write
