services:
  agent-devenv:
    hostname: agent-devenv
    image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/datadog-agent-devenv:1-arm64
    init: true
    privileged: true
    platform: linux/arm64
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ${GOPATH}/src:/home/datadog/go/src:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - omnibus-cache:/var/cache/omnibus
      - go-cache:/home/datadog/go
      - home-directory:/home/datadog
volumes:
  omnibus-cache: {}
  go-cache: {}
  home-directory: {}
